export const platformContent = {
  fa: {
    dir: 'rtl',
    localeName: 'فارسی',
    brand: 'مدیکال',
    tagline: 'همه خدمات سلامت، یک‌جا',
    heroTitle: 'سلامتی شما، همیشه در دسترس',
    heroText: 'پزشک، داروخانه، آزمایشگاه، تصویربرداری و دستیار هوشمند پزشکی در یک پلتفرم یکپارچه.',
    primaryAction: 'رزرو نوبت',
    secondaryAction: 'دستیار هوشمند',
    searchPlaceholder: 'پزشک، تخصص، دارو یا خدمت را جستجو کنید',
    servicesTitle: 'خدمات مدیکال',
    servicesSubtitle: 'هر چیزی که برای مراقبت از سلامتی نیاز دارید',
    sections: { doctors: 'پزشکان پیشنهادی', pharmacies: 'داروخانه‌های آنلاین', health: 'مراقبت هوشمند' },
    viewAll: 'مشاهده همه',
    retry: 'تلاش دوباره',
    unavailable: 'اطلاعات این بخش فعلاً در دسترس نیست.',
    home: 'خانه', doctors: 'پزشکان', pharmacy: 'داروخانه', ai: 'هوش مصنوعی', profile: 'حساب من',
    services: [
      ['doctors', 'پزشکان', 'انتخاب پزشک و نوبت آنلاین'],
      ['pharmacy', 'داروخانه', 'دارو و نسخه الکترونیک'],
      ['lab', 'آزمایشگاه', 'ثبت و پیگیری آزمایش'],
      ['imaging', 'تصویربرداری', 'مدیریت درخواست‌های تصویربرداری'],
      ['ai-chat', 'دستیار هوشمند', 'پاسخ‌گویی و راهنمایی اولیه'],
      ['appointments', 'نوبت‌های من', 'مدیریت زمان ویزیت'],
      ['records', 'پرونده سلامت', 'دسترسی امن به سوابق'],
      ['support', 'پشتیبانی', 'راهنمایی و پاسخ‌گویی'],
    ],
    safetyTitle: 'مراقبت امن و هماهنگ',
    safetyText: 'مدیکال جایگزین تشخیص پزشک یا خدمات اورژانسی نیست. در شرایط فوری با خدمات اورژانس محل زندگی تماس بگیرید.',
  },
  en: {
    dir: 'ltr', localeName: 'English', brand: 'Medikal', tagline: 'All healthcare services in one place',
    heroTitle: 'Your health, always within reach', heroText: 'Doctors, pharmacy, laboratory, imaging and an AI health assistant in one connected platform.',
    primaryAction: 'Book appointment', secondaryAction: 'AI assistant', searchPlaceholder: 'Search doctors, specialties, medicine or services',
    servicesTitle: 'Medikal services', servicesSubtitle: 'Everything you need to manage your health',
    sections: { doctors: 'Recommended doctors', pharmacies: 'Online pharmacies', health: 'Smart care' },
    viewAll: 'View all', retry: 'Try again', unavailable: 'This information is temporarily unavailable.',
    home: 'Home', doctors: 'Doctors', pharmacy: 'Pharmacy', ai: 'AI', profile: 'Account',
    services: [
      ['doctors', 'Doctors', 'Find a doctor and book online'], ['pharmacy', 'Pharmacy', 'Medicine and e-prescriptions'],
      ['lab', 'Laboratory', 'Order and track lab tests'], ['imaging', 'Imaging', 'Manage imaging requests'],
      ['ai-chat', 'AI assistant', 'Initial guidance and answers'], ['appointments', 'Appointments', 'Manage upcoming visits'],
      ['records', 'Health records', 'Secure access to your history'], ['support', 'Support', 'Help when you need it'],
    ],
    safetyTitle: 'Safe, connected care', safetyText: 'Medikal is not a replacement for a medical diagnosis or emergency services. Contact local emergency services for urgent situations.',
  },
  ar: {
    dir: 'rtl', localeName: 'العربية', brand: 'ميديكال', tagline: 'كل خدمات الصحة في مكان واحد',
    heroTitle: 'صحتك دائماً في متناولك', heroText: 'الأطباء والصيدلية والمختبر والتصوير الطبي والمساعد الصحي الذكي في منصة متكاملة.',
    primaryAction: 'حجز موعد', secondaryAction: 'المساعد الذكي', searchPlaceholder: 'ابحث عن طبيب أو تخصص أو دواء أو خدمة',
    servicesTitle: 'خدمات ميديكال', servicesSubtitle: 'كل ما تحتاجه لإدارة صحتك',
    sections: { doctors: 'أطباء مقترحون', pharmacies: 'صيدليات متصلة', health: 'رعاية ذكية' },
    viewAll: 'عرض الكل', retry: 'إعادة المحاولة', unavailable: 'هذه المعلومات غير متاحة مؤقتاً.',
    home: 'الرئيسية', doctors: 'الأطباء', pharmacy: 'الصيدلية', ai: 'الذكاء', profile: 'حسابي',
    services: [
      ['doctors', 'الأطباء', 'اختيار الطبيب وحجز موعد'], ['pharmacy', 'الصيدلية', 'الأدوية والوصفة الإلكترونية'],
      ['lab', 'المختبر', 'طلب ومتابعة التحاليل'], ['imaging', 'التصوير الطبي', 'إدارة طلبات التصوير'],
      ['ai-chat', 'المساعد الذكي', 'إرشاد أولي وإجابات'], ['appointments', 'المواعيد', 'إدارة مواعيد الزيارة'],
      ['records', 'السجل الصحي', 'الوصول الآمن إلى السجلات'], ['support', 'الدعم', 'المساعدة عند الحاجة'],
    ],
    safetyTitle: 'رعاية آمنة ومتكاملة', safetyText: 'ميديكال لا يحل محل تشخيص الطبيب أو خدمات الطوارئ. تواصل مع خدمات الطوارئ المحلية في الحالات العاجلة.',
  },
};

export function getPlatformContent(locale) {
  return platformContent[locale] || platformContent.fa;
}
