<?php
namespace App\Services\Telemedicine;
use App\Models\Appointment;use App\Models\Doctor;use App\Models\TelemedicineFile;use App\Models\TelemedicineMessage;use App\Models\TelemedicineSession;use App\Models\User;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Storage;
class TelemedicineService{
 protected $tenantId;public function __construct(){$this->tenantId=session('tenant_id');}
 private function query(){return TelemedicineSession::when($this->tenantId,fn($q)=>$q->where('tenant_id',$this->tenantId));}
 private function access(TelemedicineSession $s,$uid=null){$uid??=auth()->id();$u=User::findOrFail($uid);abort_unless($u->isAdmin()||$s->patient?->user_id===$uid||$s->doctor?->user_id===$uid,403,'دسترسی غیرمجاز به این ویزیت');}
 public function createSession(array $d):TelemedicineSession{return DB::transaction(function()use($d){$a=Appointment::with('doctor')->findOrFail($d['appointment_id']);abort_unless($a->type==='online',422,'این نوبت برای ویزیت آنلاین نیست');abort_unless($a->payment_status==='paid'||(float)$a->final_price<=0,402,'ورود به ویزیت آنلاین فقط پس از پرداخت امکان‌پذیر است');$mode=$d['metadata']['mode']??'text';abort_unless(in_array($mode,['text','video'],true),422);abort_if($mode==='text'&&!$a->doctor->offers_text_consultation,422,'ویزیت متنی برای این پزشک فعال نیست');abort_if($mode==='video'&&!$a->doctor->offers_video_consultation,422,'ویزیت تصویری برای این پزشک فعال نیست');$user=auth()->user();abort_unless($user->isAdmin()||$a->patient?->user_id===$user->id||$a->doctor?->user_id===$user->id,403,'دسترسی غیرمجاز به این نوبت');return TelemedicineSession::firstOrCreate(['appointment_id'=>$a->id],['tenant_id'=>$a->tenant_id,'patient_id'=>$a->patient_id,'doctor_id'=>$a->doctor_id,'status'=>'scheduled','notes'=>$d['notes']??null,'metadata'=>['mode'=>$mode]]);});}
 public function getSession($id):TelemedicineSession{$s=$this->query()->with(['patient','doctor.user','appointment'])->findOrFail($id);$this->access($s);return $s;}
 public function getSessionByRoom(string $room):TelemedicineSession{$s=$this->query()->where('room_name',$room)->with(['patient','doctor'])->firstOrFail();$this->access($s);return $s;}
 public function getSessions(array $f=[],int $pp=15){$q=$this->query()->with(['patient','doctor.user','appointment']);$u=auth()->user();if(!$u->isAdmin()){$q->where(function($x)use($u){$x->whereHas('patient',fn($p)=>$p->where('user_id',$u->id))->orWhereHas('doctor',fn($d)=>$d->where('user_id',$u->id));});}foreach(['doctor_id','patient_id','status'] as $k)if(isset($f[$k]))$q->where($k,$f[$k]);return $q->latest()->paginate($pp);}
 public function getDoctorSessions(int $id,array $f=[],int $pp=15){$f['doctor_id']=$id;return $this->getSessions($f,$pp);}public function getPatientSessions(int $id,array $f=[],int $pp=15){$f['patient_id']=$id;return $this->getSessions($f,$pp);}public function getActiveSessions(int $id){return $this->query()->byDoctor($id)->active()->with('patient')->get();}
 public function startSession(int $id):TelemedicineSession{$s=$this->getSession($id);abort_unless($s->doctor?->user_id===auth()->id()||auth()->user()->isAdmin(),403);abort_unless(in_array($s->status,['scheduled','waiting']),422);$s->start();return $s->fresh();}
 public function completeSession(int $id):TelemedicineSession{$s=$this->getSession($id);abort_unless($s->doctor?->user_id===auth()->id()||auth()->user()->isAdmin(),403);$s->complete();return $s->fresh();}public function cancelSession(int $id):TelemedicineSession{$s=$this->getSession($id);$s->cancel();return $s->fresh();}
 public function joinSession(int $id,int $uid):array{$s=$this->getSession($id);$this->access($s,$uid);abort_unless($s->appointment->payment_status==='paid'||(float)$s->appointment->final_price<=0,402,'پرداخت ویزیت تکمیل نشده است');if($s->status==='scheduled')$s->markAsWaiting();return ['session'=>$s->fresh(),'room_name'=>$s->room_name,'room_url'=>$s->room_url,'mode'=>$s->metadata['mode']??'text'];}
 public function sendMessage(array $d):TelemedicineMessage{$s=$this->getSession($d['session_id']);$this->access($s,$d['user_id']);return DB::transaction(fn()=>TelemedicineMessage::create(['tenant_id'=>$s->tenant_id,'session_id'=>$s->id,'user_id'=>$d['user_id'],'message'=>$d['message'],'type'=>$d['type']??'text','file_path'=>$d['file_path']??null])->fresh('user'));}
 public function getMessages(int $id,int $pp=50){$s=$this->getSession($id);return $s->messages()->with('user')->latest()->paginate($pp);}public function markMessagesAsRead(int $id,int $uid):void{TelemedicineMessage::where('session_id',$id)->where('user_id','!=',$uid)->where('is_read',false)->update(['is_read'=>true,'read_at'=>now()]);}public function getUnreadCount(int $id,int $uid):int{return TelemedicineMessage::where('session_id',$id)->where('user_id','!=',$uid)->where('is_read',false)->count();}
 public function uploadFile(array $d,$file):TelemedicineFile{$s=$this->getSession($d['session_id']);$path=$file->store('telemedicine/'.$s->id,'public');return TelemedicineFile::create(['tenant_id'=>$s->tenant_id,'session_id'=>$s->id,'user_id'=>$d['user_id'],'file_name'=>$file->getClientOriginalName(),'file_path'=>$path,'file_type'=>$file->getMimeType(),'file_size'=>$file->getSize(),'description'=>$d['description']??null]);}
 public function getFiles(int $id){$s=$this->getSession($id);return $s->files()->latest()->get();}public function deleteFile(int $id):void{$f=TelemedicineFile::findOrFail($id);$this->access($f->session);abort_unless($f->user_id===auth()->id()||auth()->user()->isAdmin(),403);Storage::disk('public')->delete($f->file_path);$f->delete();}
 public function getStats(array $f=[]):array{$q=$this->query();return ['total_sessions'=>$q->count(),'active_sessions'=>(clone $q)->active()->count(),'completed_today'=>(clone $q)->where('status','completed')->whereDate('ended_at',today())->count()];}
}