export const MOCK_FACILITIES = [
  {
    id: 1,
    type: 'pharmacy',
    name: 'داروخانه شبانه‌روزی سلامت',
    latitude: 35.7217,
    longitude: 51.3347,
    address: 'تهران، شهرک غرب، بلوار فرحزادی',
    phone: '02188000001',
    rating: 4.7,
    is_open: true,
    is_24_hours: true,
    services: ['نسخه‌پیچی', 'ارسال دارو'],
  },
  {
    id: 2,
    type: 'pharmacy',
    name: 'داروخانه نور',
    latitude: 35.7432,
    longitude: 51.3759,
    address: 'تهران، میدان ونک',
    phone: '02188000002',
    rating: 4.5,
    is_open: true,
    is_24_hours: false,
    services: ['نسخه‌پیچی'],
  },
  {
    id: 3,
    type: 'clinic',
    name: 'کلینیک تخصصی دکتر وب',
    latitude: 35.7315,
    longitude: 51.4123,
    address: 'تهران، خیابان شریعتی',
    phone: '02188000003',
    rating: 4.9,
    is_open: true,
    is_24_hours: false,
    services: ['پزشک عمومی', 'قلب', 'داخلی'],
  },
  {
    id: 4,
    type: 'clinic',
    name: 'کلینیک چشم پزشکی دید',
    latitude: 35.7068,
    longitude: 51.4011,
    address: 'تهران، خیابان مطهری',
    phone: '02188000004',
    rating: 4.6,
    is_open: false,
    is_24_hours: false,
    services: ['چشم پزشکی', 'بینایی‌سنجی'],
  },
  {
    id: 5,
    type: 'hospital',
    name: 'بیمارستان مرکزی',
    latitude: 35.6928,
    longitude: 51.3902,
    address: 'تهران، میدان ولیعصر',
    phone: '02188000005',
    rating: 4.2,
    is_open: true,
    is_24_hours: true,
    services: ['اورژانس', 'بستری'],
  },
  {
    id: 6,
    type: 'laboratory',
    name: 'آزمایشگاه تشخیص طبی پارس',
    latitude: 35.7186,
    longitude: 51.4451,
    address: 'تهران، سهروردی شمالی',
    phone: '02188000006',
    rating: 4.4,
    is_open: true,
    is_24_hours: false,
    services: ['آزمایش خون', 'نمونه‌گیری در منزل'],
  },
  {
    id: 7,
    type: 'imaging',
    name: 'مرکز تصویربرداری آفتاب',
    latitude: 35.7612,
    longitude: 51.4084,
    address: 'تهران، پاسداران',
    phone: '02188000007',
    rating: 4.8,
    is_open: true,
    is_24_hours: false,
    services: ['MRI', 'CT Scan', 'سونوگرافی'],
  },
  {
    id: 8,
    type: 'pharmacy',
    name: 'داروخانه شبانه‌روزی شرق',
    latitude: 35.7044,
    longitude: 51.4933,
    address: 'تهران، تهرانپارس',
    phone: '02188000008',
    rating: 4.3,
    is_open: true,
    is_24_hours: true,
    services: ['داروهای خاص', 'ارسال فوری'],
  },
  {
    id: 9,
    type: 'clinic',
    name: 'درمانگاه خانواده',
    latitude: 35.6754,
    longitude: 51.3572,
    address: 'تهران، نواب',
    phone: '02188000009',
    rating: 4.1,
    is_open: true,
    is_24_hours: true,
    services: ['پزشک عمومی', 'تزریقات'],
  },
];
