<?php
namespace App\Http\Controllers\Api;use App\Events\SupportMessageSent;use App\Http\Controllers\Controller;use App\Models\SupportConversation;use App\Models\SupportMessage;use Illuminate\Http\Request;
class SupportChatController extends Controller{
 private function canManage(){return auth()->user()->isAdmin();}
 private function conversation($id=null){if($this->canManage()&&$id)return SupportConversation::with(['user','assignedAdmin'])->findOrFail($id);return SupportConversation::firstOrCreate(['user_id'=>auth()->id()],['status'=>'open']);}
 public function current(){return response()->json(['success'=>true,'data'=>$this->conversation()->load(['messages.sender','assignedAdmin'])]);}
 public function index(){abort_unless($this->canManage(),403);return response()->json(['success'=>true,'data'=>SupportConversation::with(['user','assignedAdmin'])->withCount(['messages as unread_count'=>fn($q)=>$q->whereNull('read_at')->where('sender_id','!=',auth()->id())])->latest('last_message_at')->paginate(30)]);}
 public function messages(Request $r,$id=null){$c=$this->conversation($id);abort_unless($this->canManage()||$c->user_id===auth()->id(),403);SupportMessage::where('conversation_id',$c->id)->where('sender_id','!=',auth()->id())->whereNull('read_at')->update(['read_at'=>now()]);return response()->json(['success'=>true,'data'=>$c->messages()->with('sender')->latest()->paginate($r->integer('per_page',50))]);}
 public function send(Request $r,$id=null){$c=$this->conversation($id);abort_unless($this->canManage()||$c->user_id===auth()->id(),403);$d=$r->validate(['body'=>'required_without:attachment|nullable|string|max:5000','attachment'=>'nullable|file|mimes:jpg,jpeg,png,webp,pdf|max:10240']);$path=$r->hasFile('attachment')?$r->file('attachment')->store('support-chat','public'):null;$m=$c->messages()->create(['sender_id'=>auth()->id(),'body'=>$d['body']??'','type'=>$path?'file':'text','attachment_path'=>$path]);$c->update(['assigned_admin_id'=>$this->canManage()?auth()->id():$c->assigned_admin_id,'last_message_at'=>now(),'status'=>'open']);broadcast(new SupportMessageSent($m))->toOthers();return response()->json(['success'=>true,'data'=>$m->load('sender')],201);}
 public function close($id){abort_unless($this->canManage(),403);$c=SupportConversation::findOrFail($id);$c->update(['status'=>'closed']);return response()->json(['success'=>true,'data'=>$c]);}
}